#!/bin/bash

# Constants/Variables
frameDelay=0.5
animatePid=""
w=$(tput cols)
h=$(tput lines)
for (( g=0; g<$w*$h; g++)); do
	grid[$g]=0
done
temp=$(<startingGrid)
grid=(${temp/// })
echo ${grid[@]} >/dev/shm/grid

# Functions
function backLines {
	tput cuu ${h}
}

function drawBlank {
	backLines
	for (( c=1; c<=$w; c++ ))
	do
		blanker+=" "
	done
	echo -en "\r$blanker"
	for (( i=1; i<=$h; i++ ))
	do
		echo -en "$blanker"
	done
}

function draw {
	echo -en '\r'
	temp=$(</dev/shm/grid)
	grid=(${temp/// })
	for g in ${grid[@]}; do
		if [[ "$g" = "0" ]]; then
			echo -n " "
		fi
		if [[ "$g" > "0" ]]; then
			echo -n "="
		fi
	done
}

function redraw {
	backLines
	draw
}

# Animate loop
function step {
	temp=$(</dev/shm/grid)
	grid=(${temp/// })
	for (( i = $h*$w-1; i >= 0; i-- )); do
		# Acitve Blocks
		if [ ${grid[i]} == 2 ]; then
			if [ "${grid[i+w]}" == "0" ]; then
				grid[i+w]=2
				grid[i]=0
			else
				grid[i]=1
			fi
		fi
	done
	echo ${grid[@]} >/dev/shm/grid
}
function animate {
	while true; do
		step
		redraw
		sleep $frameDelay
	done
}

draw
animate &
animatePid=$!

# Input loop
while true; do
read -rsn1 input1
if [ "$input1" = "q" ]; then
	kill $animatePid
	drawBlank
	backLines
	echo -e "\nTerminetris (c) 2017 Adam Miller\n"
	exit
fi
if [ "$input1" = "a" ]; then
	temp=$(</dev/shm/grid)
	grid=(${temp/// })
	grid[(($RANDOM % ${#grid[@]}))]=2
	echo ${grid[@]} >/dev/shm/grid
fi
if [ "$input1" = $'\e' ]; then
	read -rsn1 -t 0.0001 input2
	read -rsn1 -t 0.0001 input3
	read -rsn1 -t 0.0001 input4
	if [ "$input3" = "A" ]; then
	    input1="UP"
	fi
	if [ "$input3" = "B" ]; then
	    step
	fi
	if [ "$input3" = "C" ]; then
	    input1="RIGHT"
	fi
	if [ "$input3" = "D" ]; then
	    input1="LEFT"
	fi
fi
redraw
done